[project]
name = "packedpipes"
description = "Bundles up to 16 connections of any type into a single packed pipe to keep ComfyUI workflows tidy. Adds Pipe Packer and Pipe Unpacker nodes to the utils category."
version = "1.0.4"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/id7238/ComfyUI-PackedPipes"
#  Used by Comfy Registry https://registry.comfy.org
"Bug Tracker" = "https://github.com/id7238/ComfyUI-PackedPipes/issues"

[tool.comfy]
PublisherId = "id7238"
DisplayName = "ComfyUI-PackedPipes"
Icon = "https://raw.githubusercontent.com/id7238/ComfyUI-PackedPipes/docs/assets/images/icon.jpg"
Banner ="https://raw.githubusercontent.com/id7238/ComfyUI-PackedPipes/docs/assets/images/banner.jpg"
includes = []
